version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "evansims"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Uncomment to ignore specific updates:
    # ignore:
    #   - dependency-name: "ghcr.io/mastodon/mastodon"
    #     update-types: ["version-update:semver-major"]
    #   - dependency-name: "postgres"
    #     versions: ["15.x", "16.x"]

  # Monitor GitHub Actions (if you add any workflows later)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"